<?php

namespace Clases\Soportes;

use Clases\Soportes\Soporte;

class Juego extends Soporte
{
public string $consola;
private int $minNumJugadores;
private int $maxNumJugadores;

    public function __construct(string $titulo, int $numero, string $consola, int $minNumJugadores, int $maxNumJugadores, float $precio = 5.00)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->consola=$consola;
        $this->minNumJugadores=$minNumJugadores;
        $this->maxNumJugadores=$maxNumJugadores;
    }

    public function getMinNumJugadores(): int
    {
        return $this->minNumJugadores;
    }

    public function setMinNumJugadores(int $minNumJugadores): void
    {
        $this->minNumJugadores = $minNumJugadores;
    }

    public function getMaxNumJugadores(): int
    {
        return $this->maxNumJugadores;
    }

    public function setMaxNumJugadores(int $maxNumJugadores): void
    {
        $this->maxNumJugadores = $maxNumJugadores;
    }

    public function muestraResumen()
    {
        parent::muestraResumen(); // TODO: Change the autogenerated stub
        echo " Consola: $this->consola";
        $this->muestraJugadoresPosibles();
    }

    public function muestraJugadoresPosibles(){
        if($this->getMinNumJugadores()===$this->getMaxNumJugadores()){
            echo "Para $this->minNumJugadores Jugadores";
        }
        else {
            echo "Para un minimo de $this->minNumJugadores y un maximo de $this->maxNumJugadores";
        }
    }
}