<?php

namespace Videoclub;

use Videoclub\Soporte;

class Dvd extends Soporte
{
public string $idiomas;
private string $formatoPantalla;

    public function __construct(string $titulo, int $numero, string $idiomas, string $formatoPantalla, float $precio = 5.00)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->idiomas = $idiomas;
        $this->formatoPantalla = $formatoPantalla;
    }

    public function muestraResumen()
    {
        parent::muestraResumen(); // TODO: Change the autogenerated stub
        echo "Los idiomas son: $this->idiomas, el formato de la pantalla es de:$this->formatoPantalla";
    }


}